name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    if: github.event.before != '0000000000000000000000000000000000000000'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Print debug information
        run: |
          echo "GitHub Repository: ${{ github.repository }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub SHA: ${{ github.sha }}"
